FROM debezium/connect:2.5
RUN docker-maven-download confluent kafka-connect-avro-converter "7.0.1" fd03a1436f29d39e1807e2fb6f8e415a
RUN docker-maven-download confluent kafka-connect-avro-data "7.0.1" d27f30e9eca4ef1129289c626e9ce1f1
RUN docker-maven-download confluent kafka-avro-serializer "7.0.1" c72420603422ef54d61f493ca338187c
RUN docker-maven-download confluent kafka-schema-serializer "7.0.1" 9c510db58119ef66d692ae172d5b1204
RUN docker-maven-download confluent kafka-schema-registry-client "7.0.1" 7449df1f5c9a51c3e82e776eb7814bf1