version: '2'
services:
  zookeeper:
    image: debezium/zookeeper:2.5
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888

  kafka:
    image: debezium/kafka:2.5
    ports:
     - 9092:9092
    links:
     - zookeeper
    environment:
     - ZOOKEEPER_CONNECT=zookeeper:2181

  postgres:
    image: debezium/example-postgres:2.5
    ports:
     - 5432:5432
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres

  connect:
    image: debezium/connect:2.5
    ports:
     - 8083:8083
    links:
     - kafka
     - postgres
    environment:
     - BOOTSTRAP_SERVERS=kafka:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
     - STATUS_STORAGE_TOPIC=my_connect_statuses

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8080:8080
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      # KAFKA_CLUSTERS_0_METRICS_PORT: 9997
      # KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schemaregistry0:8085
      # KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME: first
      # KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS: http://kafka-connect0:8083
      # KAFKA_CLUSTERS_1_NAME: secondLocal
      # KAFKA_CLUSTERS_1_BOOTSTRAPSERVERS: kafka1:29092
      # KAFKA_CLUSTERS_1_METRICS_PORT: 9998
      # KAFKA_CLUSTERS_1_SCHEMAREGISTRY: http://schemaregistry1:8085
      # DYNAMIC_CONFIG_ENABLED: 'true'
